apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
  namespace: rabbitmq-outbox
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-warehouse-secret
  namespace: rabbitmq-outbox
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-shipping-secret
  namespace: rabbitmq-outbox
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq-outbox
type: Opaque
data:
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
