apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
  namespace: rabbitmq-outbox
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-warehouse-secret
  namespace: rabbitmq-outbox
type: Opaque
stringData:
  username: postgres
  password: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-shipping-secret
  namespace: rabbitmq-outbox
type: Opaque
stringData:
  username: postgres
  password: postgres