apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: rabbitmq-outbox
data:
  datasource-url: jdbc:postgresql://postgres-order:5432/order_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: warehouse-service-config
  namespace: rabbitmq-outbox
data:
  datasource-url: jdbc:postgresql://postgres-warehouse:5432/warehouse_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-service-config
  namespace: rabbitmq-outbox
data:
  datasource-url: jdbc:postgresql://postgres-shipping:5432/shipping_db