apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: rabbitmq-outbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: shipping-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8022
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: shipping-service-config
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-shipping-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-shipping-secret
                  key: password
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: shipping-service-config
                  key: SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_RETRIES
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: rabbitmq-outbox
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8022
      targetPort: 8022
