apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  namespace: rabbitmq-outbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      containers:
        - name: warehouse-service
          image: warehouse-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8023
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: warehouse-service-config
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-warehouse-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-warehouse-secret
                  key: password
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: rabbitmq-outbox
spec:
  selector:
    app: warehouse-service
  ports:
    - port: 8023
      targetPort: 8023