server:
  port: 8023

spring:
  application:
    name: warehouse-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-retries: ${SPRING_RABBITMQ_LISTENER_SIMPLE_RETRY_MAX_RETRIES:3}